### PR TITLE
Bump codec dependency version to 5.x line.

### PR DESCRIPTION
**Pull request by AlexaDeWit**
I'm proposing a 3.x release line that is based on the new argonaut 5.

I specifically have a need for this as I am presently blocked from my own upgrade until this happens, or I re-implement/fork this library for myself.

This PR would provide the change.

There are actually no code changes needed, as the api remained stable for the purposes of this patch.

### CODE REVIEW

**Comment by jmackie** [comment]
Merged manually as I amended the formatting for a cleaner diff. Thanks :)

**Comment by AlexaDeWit** [comment]
Fair enough. My editor did it automatically and I had a bit of a "THIS IS BETTER ANYWAY" moment internally.

**Comment by AlexaDeWit** [comment]
I just noticed the version you chose for this is 2.0.1.

Are you sure about that? It breaks with the initial 2.0 line, which is why I suggested a 3.x branched release.

**Comment by jmackie** [comment]
My bad I did this while still half asleep, you're absolutely right. 

I've done some version juggling and you're change is picked up in version `3.0.X`.

Thanks again

**Comment by AlexaDeWit** [comment]
No probs. We're all holiday-tired, these things happen!

**Pull request closed without merging**
